### ISSUE TITLE
concord/discord.h: No such file or directory

### ISSUE THREAD

**Issue by pandasoli** [nicklausw/comparse#1]
I'm on `Ubuntu 22.04.1 LTS`.

![image](https://user-images.githubusercontent.com/76575902/221072214-9c7a8a76-091b-457a-89a4-3a4f0dedda70.png)

Yeap, I tried to run `make clean` and then `make` again.  
But nothing changed.

**Comment by nicklausw** [comment]
Will look into this; sorry for the delay. Looks like the concord library might have changed since this project was last worked on.

**Comment by nicklausw** [comment]
> Will look into this; sorry for the delay.

Well that was a lie. For 5 months, that is. Sorry about that.

Anyway, code should compile now with latest version of concord.
